name: mirror-archive-on-merge-to-default-branch

on:
  push:
    branches:
      - master

jobs:
  mirror-archive:
    runs-on:
      group: attack-data-runners
    env:
      BUCKET: attack-range-attack-data
      NEW_ATTACK_DATA_ARCHIVE_FILE: attack_data_archive/attack_data_archive.zip
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        # We must EXPLICITLY specificy lfs: true. It defaults to false
        with:
          lfs: true

      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Checkout security_content Repo
        uses: actions/checkout@v6
        with:
          repository: splunk/security_content
          path: security_content

      - name: Install contentctl-ng
        run: |
          pip install -c security_content/requirements.txt contentctl-ng

      - name: Setup AWS CLI and Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create archive of ONLY the datasets folder
        run: |
          # Use contentctl-ng to create the Attack Data Archive File
          # There is no need to make any other changes to the repo
          contentctl-ng build-attack-data-archive

          #This command builds the files:
          # - attack_data_archive/attack_data_archive.zip
          # - attack_data_archive/metadata.yml
          # We intentionally only upload the attack_data_archive.zip file to S3
          ls -lh attack_data_archive

      - name: Upload Attack data archive file to S3 Bucket
        run: |
          aws s3 cp $NEW_ATTACK_DATA_ARCHIVE_FILE  s3://$BUCKET/
